package com.zerobase.timate.entity;

public enum LogType {
	SCHEDULE_CREATE,
	SCHEDULE_UPDATE_TITLE,
	SCHEDULE_UPDATE_PLACE,
	SCHEDULE_UPDATE_MEMO,
	SCHEDULE_UPDATE_TODO,
	SCHEDULE_DELETE,
	CALENDAR_MEMBER_IN,
	CALENDAR_MEMBER_OUT
}
